name: molanalysis
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py38hd77b12b_8
  - ca-certificates=2024.7.2=haa95532_0
  - colorama=0.4.6=py38haa95532_0
  - comm=0.1.2=py38haa95532_0
  - cuda-cccl=12.6.37=0
  - cuda-cccl_win-64=12.6.37=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-profiler-api=12.6.37=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.6=3
  - debugpy=1.5.1=py38hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - gmpy2=2.1.2=py38h7f96b67_0
  - importlib-metadata=6.0.0=py38haa95532_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - ipykernel=6.19.2=py38hd4e2768_0
  - ipython=8.12.0=py38haa95532_0
  - jedi=0.18.1=py38haa95532_1
  - jpeg=9e=h2bbff1b_1
  - jupyter_client=8.1.0=py38haa95532_0
  - jupyter_core=5.3.0=py38haa95532_0
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcurand=10.3.7.37=0
  - libcurand-dev=10.3.7.37=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_0
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.39=h8cc25b3_0
  - libsodium=1.0.18=h62dcd97_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.44.2=h2bbff1b_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=2.1.3=py38h2bbff1b_0
  - matplotlib-inline=0.1.6=py38haa95532_0
  - mkl-service=2.4.0=py38h2bbff1b_0
  - mkl_fft=1.3.1=py38h277e83a_0
  - mkl_random=1.2.2=py38hf11a4ad_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.3.0=py38haa95532_0
  - nest-asyncio=1.5.6=py38haa95532_0
  - numpy=1.24.3=py38hf95b240_0
  - numpy-base=1.24.3=py38h005ec55_0
  - openjpeg=2.4.0=h4fc8c34_0
  - openssl=3.0.13=h2bbff1b_2
  - packaging=23.0=py38haa95532_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=23.0.1=py38haa95532_0
  - platformdirs=2.5.2=py38haa95532_0
  - prompt-toolkit=3.0.36=py38haa95532_0
  - psutil=5.9.0=py38h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.15.1=py38haa95532_1
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.19=h1aa4202_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch=2.3.0=py3.8_cuda11.8_cudnn8_0
  - pytorch-cuda=11.8=h24eeafa_5
  - pytorch-mutex=1.0=cuda
  - pywin32=305=py38h2bbff1b_0
  - pyyaml=6.0.1=py38h2bbff1b_0
  - pyzmq=25.0.2=py38hd77b12b_0
  - setuptools=67.8.0=py38haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.12=py38haa95532_0
  - tornado=6.2=py38h2bbff1b_0
  - traitlets=5.7.1=py38haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.38.4=py38haa95532_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.4=hd77b12b_0
  - zipp=3.11.0=py38haa95532_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.5=hd43e919_2
  - pip:
      - alabaster==0.7.13
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - atflow==0.0.3
      - babel==2.16.0
      - bcrypt==4.0.1
      - blinker==1.8.2
      - cellpose==2.2.2
      - certifi==2023.5.7
      - cffi==1.15.1
      - charset-normalizer==3.1.0
      - click==8.1.3
      - commonmark==0.9.1
      - contourpy==1.0.7
      - cryptography==41.0.1
      - cycler==0.11.0
      - datajoint==0.14.1
      - docutils==0.20.1
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.2
      - facemap==1.0.1
      - fastremap==1.13.5
      - filelock==3.12.0
      - flask==3.0.3
      - fonttools==4.39.4
      - fsspec==2024.6.1
      - future==1.0.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - h5py==3.8.0
      - idna==3.4
      - imagecodecs==2023.3.16
      - imageio==2.31.1
      - imagesize==1.4.1
      - importlib-resources==5.12.0
      - iniconfig==2.0.0
      - intel-openmp==2021.4.0
      - ipympl==0.9.3
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.6
      - itsdangerous==2.2.0
      - jinja2==3.1.2
      - joblib==1.2.0
      - jupyterlab-widgets==3.0.7
      - kiwisolver==1.4.4
      - lazy-loader==0.3
      - lipstick==0.0.7
      - llvmlite==0.40.0
      - matplotlib==3.7.1
      - matplotlib-scalebar==0.8.1
      - mei==0.0.0
      - minio==7.2.8
      - mkl==2021.4.0
      - natsort==8.3.1
      - networkx==2.6.3
      - neuralpredictors==0.3.0
      - nnfabrik==0.2.1
      - numba==0.57.0
      - oauthlib==3.2.2
      - opencv-python-headless==4.7.0.72
      - openpyxl==3.1.2
      - otumat==0.3.1
      - pandas==1.5.3
      - paramiko==3.2.0
      - pillow==9.5.0
      - pluggy==1.5.0
      - pycparser==2.21
      - pycryptodome==3.20.0
      - pydot==3.0.1
      - pylustrator==1.3.0
      - pymysql==1.1.1
      - pynacl==1.5.0
      - pyparsing==3.0.9
      - pyqt5==5.15.9
      - pyqt5-plugins==5.15.9.2.3
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.12.1
      - pyqt5-tools==5.15.9.3.3
      - pyqtgraph==0.13.3
      - pytest==8.3.2
      - python-dotenv==1.0.0
      - python-graphviz==0.20.3
      - pytorch-sphinx-theme==0.0.19
      - pytz==2023.3
      - pywavelets==1.4.1
      - qt5-applications==5.15.2.2.3
      - qt5-tools==5.15.2.1.3
      - qtawesome==1.2.3
      - qtpy==2.3.1
      - rastermap==0.9.1
      - recommonmark==0.7.1
      - requests==2.31.0
      - roifile==2023.5.12
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - sbxreader==0.2.2
      - scanimage-tiff-reader==1.4.1.3
      - scikit-image==0.19.3
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - smmap==5.0.1
      - snowballstemmer==2.2.0
      - sphinx==7.1.2
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - statannot==0.2.3
      - statannotations==0.6.0
      - suite2p==0.13.0
      - tbb==2021.13.1
      - threadpoolctl==3.1.0
      - tifffile==2023.4.12
      - tomli==2.0.1
      - torch==2.0.1
      - torchaudio==2.3.0
      - torchvision==0.18.0
      - tqdm==4.65.0
      - typing-extensions==4.12.2
      - tzdata==2023.3
      - urllib3==2.0.2
      - watchdog==4.0.2
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.7
prefix: C:\Users\asimo\.conda\envs\molanalysis
